// @auth
export const AUTHORIZATION_REQUEST = '@auth/AUTHORIZATION_REQUEST';
export const AUTHORIZATION_SUCCESS = '@auth/AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILURE = '@auth/AUTHORIZATION_FAILURE';
export const LOGOUT = '@auth/LOGOUT';

// @characters
export const CHARACTER_REQUEST = '@character/CHARACTER_REQUEST';
export const CHARACTER_SUCCESS = '@character/CHARACTER_SUCCESS';
export const CHARACTER_FAILURE = '@character/CHARACTER_FAILURE';
export const CLEAR_CHARACTER_SELECTED = '@character/CLEAR_CHARACTER_SELECTED';
export const CHARACTERS_PAGINATION_REQUEST =
  '@character/CHARACTERS_PAGINATION_REQUEST';
export const CHARACTERS_PAGINATION_SUCCESS =
  '@character/CHARACTERS_PAGINATION_SUCCESS';
